### ISSUE TITLE
API 重复数据问题

### ISSUE THREAD

**Issue by Song-s-z** [jinxZz/zhihuimage#1]
const Url = "https://www.zhihu.com/api/v4/questions/{QUESTION_ID}/answers?include=content&limit={LIMIT}&offset={OFFSET}&sort_by=default"
最近知乎策略似乎调整了，单抓这个API 会抓到重复数据，刚试了下，例如下面这个
https://www.zhihu.com/api/v4/questions/29815580/answers?include=content&limit=5&offset=6&sort_by=default
这个问题下一共16个答案，但是却能抓到offset=6，而且还没有结束

**Comment by jinxZz** [comment]
offset是回答的偏移量，offset=6就从7个问题开始查询，重复应该是offset偏移不一样但是查到同一页了

**Comment by Song-s-z** [comment]
已修正，是的，现在的策略和以前不一样，偏移量已经不能递增了。

**Comment by jinxZz** [comment]
@Song-s-z 不太了解以前😂
